package rtc

import (
	"context"
	"fmt"
	"time"

	"com.papchenko.audio.server/audio"
	"com.papchenko.audio.server/utils"
	"github.com/pion/webrtc/v3"
	"github.com/pion/webrtc/v3/pkg/media"
)

//StartWebRtc - initializes webRTC engine, ready to get opus samples
func StartWebRtc(sampleData <-chan audio.SampleData) {

	// Create a new RTCPeerConnection
	m := webrtc.MediaEngine{}

	if err := m.RegisterCodec(webrtc.RTPCodecParameters{
		RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: "audio/opus", ClockRate: 48000, Channels: 2, SDPFmtpLine: "stereo=1", RTCPFeedback: nil},
		PayloadType:        111,
	}, webrtc.RTPCodecTypeAudio); err != nil {
		panic(err)
	}

	api := webrtc.NewAPI(webrtc.WithMediaEngine(&m))

	peerConnection, err := api.NewPeerConnection(webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{},
			},
		},
	})

	if err != nil {
		panic(err)
	}
	iceConnectedCtx, iceConnectedCtxCancel := context.WithCancel(context.Background())

	// Create a audio track
	audioTrack, audioTrackErr := webrtc.NewTrackLocalStaticSample(webrtc.RTPCodecCapability{MimeType: "audio/opus"}, "audio", "pion")
	if audioTrackErr != nil {
		panic(audioTrackErr)
	}
	if _, audioTrackErr = peerConnection.AddTrack(audioTrack); audioTrackErr != nil {
		panic(audioTrackErr)
	}

	go func() {

		// Wait for connection established
		<-iceConnectedCtx.Done()

		for {

			data := <-sampleData
			var sampleDuration time.Duration = 10000000

			if oggErr := audioTrack.WriteSample(media.Sample{Data: data.Samples, Duration: sampleDuration}); oggErr != nil {
				panic(oggErr)
			}

			time.Sleep(sampleDuration)
		}
	}()

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
		if connectionState == webrtc.ICEConnectionStateConnected {
			iceConnectedCtxCancel()
		}
	})

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	utils.Decode("eyJ0eXBlIjoib2ZmZXIiLCJzZHAiOiJ2PTBcclxubz0tIDU5MzI4NTc1MjYwMDQ1OTgzMjQgMiBJTiBJUDQgMTI3LjAuMC4xXHJcbnM9LVxyXG50PTAgMFxyXG5hPWdyb3VwOkJVTkRMRSAwIDFcclxuYT1tc2lkLXNlbWFudGljOiBXTVNcclxubT12aWRlbyA0NDMwOSBVRFAvVExTL1JUUC9TQVZQRiA5NiA5NyA5OCA5OSAxMDIgMTI1IDEwNFxyXG5jPUlOIElQNCAxOTIuMTY4LjEuNVxyXG5hPXJ0Y3A6OSBJTiBJUDQgMC4wLjAuMFxyXG5hPWNhbmRpZGF0ZToyMTExNTY4MjEgMSB1ZHAgMjExMzkzNzE1MSAxOTIuMTY4LjEuNSA0NDMwOSB0eXAgaG9zdCBnZW5lcmF0aW9uIDAgbmV0d29yay1jb3N0IDk5OVxyXG5hPWljZS11ZnJhZzpBbktwXHJcbmE9aWNlLXB3ZDpiRnVvN2l2UTBqd3FlT2xYNnQ2V2M5OWNcclxuYT1pY2Utb3B0aW9uczp0cmlja2xlXHJcbmE9ZmluZ2VycHJpbnQ6c2hhLTI1NiBCNzozQTpDNDo1QzowRDpGQTpEQzpFRDpBNTpDRDo3MzpERjpBNDoxRDpGMDpCQTo4Qjo2MDo2Rjo2OTpERTpEMDo2MDowQjoxMDowMToyODoxMDpDQjpFNjpCRjpCQlxyXG5hPXNldHVwOmFjdHBhc3NcclxuYT1taWQ6MFxyXG5hPWV4dG1hcDoxIHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnRvZmZzZXRcclxuYT1leHRtYXA6MiBodHRwOi8vd3d3LndlYnJ0Yy5vcmcvZXhwZXJpbWVudHMvcnRwLWhkcmV4dC9hYnMtc2VuZC10aW1lXHJcbmE9ZXh0bWFwOjMgdXJuOjNncHA6dmlkZW8tb3JpZW50YXRpb25cclxuYT1leHRtYXA6NCBodHRwOi8vd3d3LmlldGYub3JnL2lkL2RyYWZ0LWhvbG1lci1ybWNhdC10cmFuc3BvcnQtd2lkZS1jYy1leHRlbnNpb25zLTAxXHJcbmE9ZXh0bWFwOjUgaHR0cDovL3d3dy53ZWJydGMub3JnL2V4cGVyaW1lbnRzL3J0cC1oZHJleHQvcGxheW91dC1kZWxheVxyXG5hPWV4dG1hcDo2IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L3ZpZGVvLWNvbnRlbnQtdHlwZVxyXG5hPWV4dG1hcDo3IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L3ZpZGVvLXRpbWluZ1xyXG5hPWV4dG1hcDo4IGh0dHA6Ly93d3cud2VicnRjLm9yZy9leHBlcmltZW50cy9ydHAtaGRyZXh0L2NvbG9yLXNwYWNlXHJcbmE9ZXh0bWFwOjkgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c2RlczptaWRcclxuYT1leHRtYXA6MTAgdXJuOmlldGY6cGFyYW1zOnJ0cC1oZHJleHQ6c2RlczpydHAtc3RyZWFtLWlkXHJcbmE9ZXh0bWFwOjExIHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnNkZXM6cmVwYWlyZWQtcnRwLXN0cmVhbS1pZFxyXG5hPXNlbmRyZWN2XHJcbmE9bXNpZDotIGM5NzI2NzMyLTI1ZTQtNGYxMS1iZmRiLWRkM2U0ZDk4ZGM4NFxyXG5hPXJ0Y3AtbXV4XHJcbmE9cnRjcC1yc2l6ZVxyXG5hPXJ0cG1hcDo5NiBWUDgvOTAwMDBcclxuYT1ydGNwLWZiOjk2IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6OTYgdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjo5NiBjY20gZmlyXHJcbmE9cnRjcC1mYjo5NiBuYWNrXHJcbmE9cnRjcC1mYjo5NiBuYWNrIHBsaVxyXG5hPXJ0cG1hcDo5NyBydHgvOTAwMDBcclxuYT1mbXRwOjk3IGFwdD05NlxyXG5hPXJ0cG1hcDo5OCBWUDkvOTAwMDBcclxuYT1ydGNwLWZiOjk4IGdvb2ctcmVtYlxyXG5hPXJ0Y3AtZmI6OTggdHJhbnNwb3J0LWNjXHJcbmE9cnRjcC1mYjo5OCBjY20gZmlyXHJcbmE9cnRjcC1mYjo5OCBuYWNrXHJcbmE9cnRjcC1mYjo5OCBuYWNrIHBsaVxyXG5hPWZtdHA6OTggcHJvZmlsZS1pZD0wXHJcbmE9cnRwbWFwOjk5IHJ0eC85MDAwMFxyXG5hPWZtdHA6OTkgYXB0PTk4XHJcbmE9cnRwbWFwOjEwMiByZWQvOTAwMDBcclxuYT1ydHBtYXA6MTI1IHJ0eC85MDAwMFxyXG5hPWZtdHA6MTI1IGFwdD0xMDJcclxuYT1ydHBtYXA6MTA0IHVscGZlYy85MDAwMFxyXG5hPXNzcmMtZ3JvdXA6RklEIDQyMTk0MjAwNTYgMTcxNTcyNjcxMFxyXG5hPXNzcmM6NDIxOTQyMDA1NiBjbmFtZTpmWnpNOG1sWW9hZ3JTcDRQXHJcbmE9c3NyYzo0MjE5NDIwMDU2IG1zaWQ6LSBjOTcyNjczMi0yNWU0LTRmMTEtYmZkYi1kZDNlNGQ5OGRjODRcclxuYT1zc3JjOjQyMTk0MjAwNTYgbXNsYWJlbDotXHJcbmE9c3NyYzo0MjE5NDIwMDU2IGxhYmVsOmM5NzI2NzMyLTI1ZTQtNGYxMS1iZmRiLWRkM2U0ZDk4ZGM4NFxyXG5hPXNzcmM6MTcxNTcyNjcxMCBjbmFtZTpmWnpNOG1sWW9hZ3JTcDRQXHJcbmE9c3NyYzoxNzE1NzI2NzEwIG1zaWQ6LSBjOTcyNjczMi0yNWU0LTRmMTEtYmZkYi1kZDNlNGQ5OGRjODRcclxuYT1zc3JjOjE3MTU3MjY3MTAgbXNsYWJlbDotXHJcbmE9c3NyYzoxNzE1NzI2NzEwIGxhYmVsOmM5NzI2NzMyLTI1ZTQtNGYxMS1iZmRiLWRkM2U0ZDk4ZGM4NFxyXG5tPWF1ZGlvIDQ4NDMxIFVEUC9UTFMvUlRQL1NBVlBGIDExMSAxMDMgOSAwIDggMTA1IDEzIDExMCAxMTMgMTI2XHJcbmM9SU4gSVA0IDE5Mi4xNjguMS41XHJcbmE9cnRjcDo5IElOIElQNCAwLjAuMC4wXHJcbmE9Y2FuZGlkYXRlOjIxMTE1NjgyMSAxIHVkcCAyMTEzOTM3MTUxIDE5Mi4xNjguMS41IDQ4NDMxIHR5cCBob3N0IGdlbmVyYXRpb24gMCBuZXR3b3JrLWNvc3QgOTk5XHJcbmE9aWNlLXVmcmFnOkFuS3BcclxuYT1pY2UtcHdkOmJGdW83aXZRMGp3cWVPbFg2dDZXYzk5Y1xyXG5hPWljZS1vcHRpb25zOnRyaWNrbGVcclxuYT1maW5nZXJwcmludDpzaGEtMjU2IEI3OjNBOkM0OjVDOjBEOkZBOkRDOkVEOkE1OkNEOjczOkRGOkE0OjFEOkYwOkJBOjhCOjYwOjZGOjY5OkRFOkQwOjYwOjBCOjEwOjAxOjI4OjEwOkNCOkU2OkJGOkJCXHJcbmE9c2V0dXA6YWN0cGFzc1xyXG5hPW1pZDoxXHJcbmE9ZXh0bWFwOjE0IHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnNzcmMtYXVkaW8tbGV2ZWxcclxuYT1leHRtYXA6MiBodHRwOi8vd3d3LndlYnJ0Yy5vcmcvZXhwZXJpbWVudHMvcnRwLWhkcmV4dC9hYnMtc2VuZC10aW1lXHJcbmE9ZXh0bWFwOjQgaHR0cDovL3d3dy5pZXRmLm9yZy9pZC9kcmFmdC1ob2xtZXItcm1jYXQtdHJhbnNwb3J0LXdpZGUtY2MtZXh0ZW5zaW9ucy0wMVxyXG5hPWV4dG1hcDo5IHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnNkZXM6bWlkXHJcbmE9ZXh0bWFwOjEwIHVybjppZXRmOnBhcmFtczpydHAtaGRyZXh0OnNkZXM6cnRwLXN0cmVhbS1pZFxyXG5hPWV4dG1hcDoxMSB1cm46aWV0ZjpwYXJhbXM6cnRwLWhkcmV4dDpzZGVzOnJlcGFpcmVkLXJ0cC1zdHJlYW0taWRcclxuYT1zZW5kcmVjdlxyXG5hPW1zaWQ6LSA1YjA5MjZkOC1lODYzLTQzMjYtOWExNS1kMjQwNDgzZTk5NmRcclxuYT1ydGNwLW11eFxyXG5hPXJ0cG1hcDoxMTEgb3B1cy80ODAwMC8yXHJcbmE9cnRjcC1mYjoxMTEgdHJhbnNwb3J0LWNjXHJcbmE9Zm10cDoxMTEgbWlucHRpbWU9MTA7dXNlaW5iYW5kZmVjPTFcclxuYT1ydHBtYXA6MTAzIElTQUMvMTYwMDBcclxuYT1ydHBtYXA6OSBHNzIyLzgwMDBcclxuYT1ydHBtYXA6MCBQQ01VLzgwMDBcclxuYT1ydHBtYXA6OCBQQ01BLzgwMDBcclxuYT1ydHBtYXA6MTA1IENOLzE2MDAwXHJcbmE9cnRwbWFwOjEzIENOLzgwMDBcclxuYT1ydHBtYXA6MTEwIHRlbGVwaG9uZS1ldmVudC80ODAwMFxyXG5hPXJ0cG1hcDoxMTMgdGVsZXBob25lLWV2ZW50LzE2MDAwXHJcbmE9cnRwbWFwOjEyNiB0ZWxlcGhvbmUtZXZlbnQvODAwMFxyXG5hPXNzcmM6MjMzOTcyMDI4NiBjbmFtZTpmWnpNOG1sWW9hZ3JTcDRQXHJcbmE9c3NyYzoyMzM5NzIwMjg2IG1zaWQ6LSA1YjA5MjZkOC1lODYzLTQzMjYtOWExNS1kMjQwNDgzZTk5NmRcclxuYT1zc3JjOjIzMzk3MjAyODYgbXNsYWJlbDotXHJcbmE9c3NyYzoyMzM5NzIwMjg2IGxhYmVsOjViMDkyNmQ4LWU4NjMtNDMyNi05YTE1LWQyNDA0ODNlOTk2ZFxyXG4ifQ==", &offer)

	// Set the remote SessionDescription
	if err = peerConnection.SetRemoteDescription(offer); err != nil {
		panic(err)
	}

	// Create answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		panic(err)
	}

	// Create channel that is blocked until ICE Gathering is complete
	gatherComplete := webrtc.GatheringCompletePromise(peerConnection)

	// Sets the LocalDescription, and starts our UDP listeners
	if err = peerConnection.SetLocalDescription(answer); err != nil {
		panic(err)
	}

	// Block until ICE Gathering is complete, disabling trickle ICE
	// we do this because we only can exchange one signaling message
	// in a production application you should exchange ICE Candidates via OnICECandidate
	<-gatherComplete

	// Output the answer in base64 so we can paste it in browser
	fmt.Println(utils.Encode(*peerConnection.LocalDescription()))

	// Block forever
	select {}
}
